spring:
#  datasource:
#    # 对于 Druid,仅能配置以下基本参数,如果要配置其他参数,需要采用 JavaConfig 的方式
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://10.176.116.0:33066/db_vip_base?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useTimezone=true&useLegacyDatetimeCode=false&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    username: vip
#    password: 123456
  # 自定义配置
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.176.116.0:33066/db_vip_base?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useTimezone=true&useLegacyDatetimeCode=false&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: vip
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 1200
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 160000
    maxEvictableIdleTimeMillis: 230000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    keepAlive: true
    keepAliveBetweenTimeMillis: 120000

#druid:
#  url: jdbc:mysql://10.176.116.0:33066/db_vip_base?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useTimezone=true&useLegacyDatetimeCode=false&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#  username: vip
#  password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml